### DISCUSSION TITLE
Openai settings in prompt templates

### DISCUSSION THREAD

**Discussion by briansunter** [briansunter/logseq-plugin-gpt3-openai#192] [Ideas]
Support customizing things like model, temperature, token count, frequency penalty, stop sequences, etc in the prompt templates.

```toml
[summarize-text]
name = "Summarize Text"
description = "Summarize a text document"
temperature = 0.7
model = "text-davinci-002'
maximumLength = 500
prompt = '''
Summarize text:
'''

```
